name: calculatorx # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: 'v1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Just a culculator with an X. # 79 char long summary
description: |
  This is my simple Calculator wich will be coded when i am board. Thy mystic thing on it is, that it has an X. This means eXtream cool project when the brogrammer is bored.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  test:
    command: usr/lib/jvm/java-14-openjdk-amd64/jre/bin/java -jar $SNAP/calculatorx/CalculatorX.jar
    plugs: [unity7, network, home]
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/default-java
      CLASSPATH: $SNAP/jar/SnapTest.jar
      PATH: $SNAP/usr/lib/jvm/default-java/bin:$PATH

parts:
  calculatorx:
    # See 'snapcraft plugins'
    plugin: dump
  stage-packages: [openjdk-14-jre, openjdk-14-demo]
    source: https://github.com/GregorBoxer-sudo/CalculatorX.git
    
